### ISSUE TITLE
Access custom post type in WP REST API

### ISSUE THREAD

**Issue by dreamorosi** [rilwis/mb-custom-post-type#10]
Hi, thanks for developing this plugin.

I was wondering if was possible to expose the custom posts in the Wordpress json REST API and if so how? At the moment I'm using WP 4.7 along with Meta Box, MB Custom Post Type and MB Rest API but I can only see normal posts/pages.

Thanks in advance

**Comment by malfborger** [comment]
if you'd do this manually you would add 
`'rest_controller_class' => 'WP_REST_Terms_Controller',` to your register_taxonomy. Hope you will enable this in the plugins @rilwis

**Comment by rilwis** [comment]
Updated the plugin :)
