### ISSUE TITLE
Export PHP code

### ISSUE THREAD

**Issue by eriktdesign** [rilwis/mb-custom-post-type#12]
The **Code** tab in the Meta Box Builder plugin was the reason that I decided to start using it. It's a great tool to get things going quickly, and I can export the code and add it to my theme when I'm done to prevent my clients from breaking anything.

I'd like to request the same feature in the mb-custom-post-type plugin. I imagine it would be implemented in a similar way.

**Comment by rilwis** [comment]
Nice. Thanks for your suggestion. I will try to implement it!

**Comment by rilwis** [comment]
This is done in 0f59d888342470fbfe2ac389804292a425858784. Thanks @truongwp for your work!
