### ISSUE TITLE
Menu position isn't working 

### ISSUE THREAD

**Issue by nxtzero** [rilwis/mb-custom-post-type#14]
I noticed "menu_position" isn't working because Wordpress demands it to be Integer so I changed code in line 84 of file: "/inc/post-type/register.php":
`$data = is_numeric( $data ) ? ( 1 === intval( $data ) ? true : false ) : $data;`

to:
`$data = ( $key === 'args_menu_position' ? intval($data) : ( is_numeric( $data ) ? ( 1 === intval( $data ) ? true : false ) : $data ) );`

I would appreciate if you could change the plugin code.

**Comment by truongwp** [comment]
Hi @nxtzero,
Thank you for your report. We fixed it.

**Comment by nxtzero** [comment]
Hi,

Thank you. Any estimated date to update it on wordpress.org plugins ?

Greetings,
nxtzero

**Comment by truongwp** [comment]
We are testing some new features. It will be updated soon. Thank you.
