### ISSUE TITLE
Categories and/or Tags Support for Custom Post Types

### ISSUE THREAD

**Issue by readej** [rilwis/mb-custom-post-type#6]
I would like to add categories and tags support to the custom post types that are setup through this plugin. Below is my response to a support topic on wordpress.org for this request. The support topic can be viewed here: https://wordpress.org/support/topic/categories-support?replies=4

If you add the following code to your theme's functions.php, a new meta beta will appear when creating a custom post type:
`function cpt_support_for_cats_and_tags_meta_boxes( $meta_boxes ) {
	// Taxonomies
	$args_prefix  = 'args_';
	$meta_boxes[] = array(
		'id'       => 'taxonomies',
		'title'    => __( 'Supports Categories/Tags', 'mb-custom-post-type' ),
		'pages'    => array( 'mb-post-type' ),
		'priority' => 'low',
		'context'  => 'side',
		'fields'   => array(
			array(
				'id'      => $args_prefix . 'taxonomies',
				'type'    => 'checkbox_list',
				'options' => array(
					'category' => __( 'Categories', 'mb-custom-post-type' ),
					'post_tag' => __( 'Tags', 'mb-custom-post-type' ),
				),
			),
		),
	);
	return $meta_boxes;
}
add_filter( 'rwmb_meta_boxes', 'cpt_support_for_cats_and_tags_meta_boxes' );`

The catch is that you have to select BOTH categories AND tags.

This is because of line 87 in \inc\post-type\register.php
`$data = 1 == count( $value ) ? $value[0] : $value;`

When you check only one of the check boxes either categories or tags, the count() of the array for taxonomies is 1 and $data becomes either 'category' or 'post_tag'. Then when the post type is registered on line 57, `$args['taxonomies']` is not an array like it is expecting.

**Comment by rilwis** [comment]
Hi, I think **Category** and **Tag** are just 2 predefined taxonomies and are used for **posts**. It would be a confusion if custom post type doesn't have categories or tags. The plugin now allows you to define custom taxonomies and assign them to post types (so the relation is taxonomy --> post type, not post type --> taxonomy) and it makes more sense.

**Comment by readej** [comment]
The issue is that I want to use the 2 predefined taxonomies for my custom post types.

The predefined taxonomies cannot be attached to a custom post type created by this plugin at this time. I am trying to remedy that.

**Comment by rilwis** [comment]
I got it. Will add that in the next version.

**Comment by readej** [comment]
Thank you! Could you tell me when the next version will most-likely come out?

Thanks again,

**Comment by rilwis** [comment]
New version was just released. Enjoy the plugin :)

**Comment by readej** [comment]
Thank you for including the feature in the new release! However, you are having the same problem I had. A user has to select BOTH category AND tag in order for either to show in the custom post type.

This is because of line 89 in inc/post-type/register.php
`$data = 1 == count( $value ) ? $value[0] : $value;`

When you check only one of the check boxes either categories or tags, the count() of the array for taxonomies is 1 and $data becomes either 'category' or 'post_tag'. Then when the post type is registered on line 57, $args['taxonomies'] is not an array like it is [expecting](https://codex.wordpress.org/Function_Reference/register_post_type#Arguments).

**Comment by readej** [comment]
Here is some code to fix the issue.

Replace this:
```
$data = 1 == count( $value ) ? $value[0] : $value;
```
With this:
```
if ($key != 'args_taxonomies' )
    $data = 1 == count( $value ) ? $value[0] : $value;
else
    $data = $value;
```

**Comment by rilwis** [comment]
Thanks for your help! I've just updated the code with the fix.
