### ISSUE TITLE
hide main post type 'mb-post-type' option

### ISSUE THREAD

**Issue by unetics** [rilwis/mb-custom-post-type#7]
It would be great if you could add a setting ore even a hook that would allow to hide this post type conditionally, 
For example i love your plugin and use it regularly but all my site are for customers that i don't want to see/play with the settings so i would make it only visible to my username.

**Comment by rilwis** [comment]
Hi, I think you can hide the menu with the [Hide Admin Menu](https://codecanyon.net/item/wordpress-hide-admin-menu-plugin/290744?ref=rilwis) plugin (premium) or [Adminimize](https://wordpress.org/plugins/adminimize/) plugin (free).
