### ISSUE TITLE
Allow to set "Prepend Permalink Structure" for post type registration

### ISSUE THREAD

**Issue by pisc-software** [rilwis/mb-custom-post-type#9]
Thanks for this extension, I want to make the following contribution (without Git Pull request):

I needed an option to allow to control the "prepend permalink structure" flag on the Custom Post Type registratiopn, and with a few code lines it seems to be added easily.

Maybe this can be included in a future update, as I think it will be a valuable addition to this and for others:

[prepend-permalink-option.zip](https://github.com/rilwis/mb-custom-post-type/files/250173/prepend-permalink-option.zip)

Thanks.

**Comment by rilwis** [comment]
Thanks for your contribution. I will check the code and include it.

**Comment by rilwis** [comment]
Just pushed a new update to .org, which has 2 options for custom rewrite slug and `with_front`.

**Comment by pisc-software** [comment]
Thanks for this. Actually we also added this option to the Taxonomies, see files attached. Tested and works so far.

[Taxonomies.zip](https://github.com/rilwis/mb-custom-post-type/files/272679/Taxonomies.zip)
